### ISSUE TITLE
Discussion: Merits of grouping width & height together instead of alphabetical

### ISSUE THREAD

**Issue by dan-gamble** [standard-css/standard-css#1]
**Current**
```css
.current {
  display: block;
  height: 10px;
  margin: 10px;
  padding: 10px 20px;
  width: 10px;
}
```

**Potential/Proposed**
```css
.potential {
  display: block;
  width: 10px;
  height: 10px;
  margin: 10px;
  padding: 10px 20px;
}
```

I personally prefer the 1st style main reason being i think it looks nicer aesthetically. Aesthetics though isn't reason enough to have a code style. I think the `proposed` style probably makes more sense because:

* It puts more commonly used properties together and higher in the group
* Width comes first because CSS syntax tends to use width before height i.e. `background-size`
